---
- name: Disable services
  ansible.builtin.systemd:
    name: dnf-makecache.timer
    state: stopped
    enabled: false

- name: Disable services
  ansible.builtin.systemd:
    name: packagekit
    state: stopped
    enabled: false

- name: Disable services
  ansible.builtin.systemd:
    name: packagekit-offline-update
    state: stopped
    enabled: false

- name: GNOME & timedatectl
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.software download-updates false
      timedatectl set-timezone Etc/UTC
      timedatectl set-ntp false
...
