---
- name: Disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - dnf-makecache.timer
    - packagekit.service
    - packagekit-offline-update.service

- name: GNOME & timedatectl
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.software download-updates false
      timedatectl set-timezone Etc/UTC
      timedatectl set-ntp false
...
