---
- name: Enable ControlPort
  ansible.builtin.lineinfile:
    path: "/etc/tor/torrc"
    regexp: "^#ControlPort 9051$"
    line: "ControlPort 9051"

- name: Enable HiddenServiceDir
  ansible.builtin.lineinfile:
    path: "/etc/tor/torrc"
    line: "HiddenServiceDir /var/lib/tor/hidden_service/"
    state: present
    insertafter: "^############### This section is just for location-hidden services ###$"

- name: Define HiddenServiceVersion
  ansible.builtin.lineinfile:
    path: "/etc/tor/torrc"
    line: "HiddenServiceVersion 3"
    state: present
    insertafter: "^HiddenServiceDir /var/lib/tor/hidden_service/$"

- name: Enable Web HiddenServicePort
  ansible.builtin.lineinfile:
    path: "/etc/tor/torrc"
    line: "HiddenServicePort 80 127.0.0.1:80"
    state: present
    insertafter: "^HiddenServiceVersion 3$"

- name: Enable SSH HiddenServicePort
  ansible.builtin.lineinfile:
    path: "/etc/tor/torrc"
    line: "HiddenServicePort 22 127.0.0.1:22"
    state: present
    insertafter: "^HiddenServicePort 80 127.0.0.1:80"

- name: "Start & Disable Tor"
  ansible.builtin.systemd:
    name: tor.service
    state: started
    enabled: false
...
